//= error

fun main(): Unit {
    std::call("foo");
}

fun foo(a: Int32): Unit {
    println(a.toString());
}
